## 1 Simple numpy function

In [1]:
import numpy as np

In [3]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 2 Linear regression with one variable

In [4]:
import pandas as pd

In [13]:
chain_resturant = pd.read_csv("Uni_linear.txt", names= ["Population", "Profit"])

In [15]:
chain_resturant.head()

Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [16]:
chain_resturant.describe()

Population     Profit
count   97.000000  97.000000
mean     8.159800   5.839135
std      3.869884   5.510262
min      5.026900  -2.680700
25%      5.707700   1.986900
50%      6.589400   4.562300
75%      8.578100   7.046700
max     22.203000  24.147000

## 2.1 Plotting the Data

In [17]:
import seaborn as sns